import type { AccountBrandGroup } from '@/types/accountMonitoringUi';

/** Mock data — ganti dengan Supabase nanti */
export const ACCOUNT_BRAND_MOCK: AccountBrandGroup[] = [
  {
    id: 'brand-a',
    brandLabel: 'A',
    brandName: 'LuxTrade',
    accountCount: 3,
    standardGroupCount: 3,
    misalignedCount: 2,
    emptySlots: [],
    accounts: [
      {
        id: 'a1',
        platform: 'whatsapp',
        accountName: '客服-小美',
        phoneOrUsername: '+60198765432',
        brandName: 'LuxTrade',
        status: 'active',
        groupsCurrent: 3,
        groupsTotal: 3,
        adminCurrent: 3,
        adminTotal: 3,
        syncState: 'synced',
      },
      {
        id: 'a2',
        platform: 'whatsapp',
        accountName: '运营-001',
        phoneOrUsername: '+60123456789',
        brandName: 'LuxTrade',
        status: 'logout',
        groupsCurrent: 2,
        groupsTotal: 3,
        adminCurrent: 2,
        adminTotal: 3,
        syncState: 'synced',
      },
      {
        id: 'a3',
        platform: 'telegram',
        accountName: 'TG Bot-01',
        phoneOrUsername: '@LuxTradeBot',
        brandName: 'LuxTrade',
        status: 'active',
        groupsCurrent: 3,
        groupsTotal: 3,
        adminCurrent: 3,
        adminTotal: 3,
        syncState: 'synced',
      },
    ],
  },
  {
    id: 'brand-b',
    brandLabel: 'B',
    brandName: 'GoldenBet',
    accountCount: 2,
    standardGroupCount: 2,
    misalignedCount: 0,
    emptySlots: [],
    accounts: [
      {
        id: 'b1',
        platform: 'whatsapp',
        accountName: 'CS-Golden',
        phoneOrUsername: '+60111222333',
        brandName: 'GoldenBet',
        status: 'active',
        groupsCurrent: 2,
        groupsTotal: 2,
        adminCurrent: 2,
        adminTotal: 2,
        syncState: 'synced',
      },
      {
        id: 'b2',
        platform: 'telegram',
        accountName: 'TG-Golden',
        phoneOrUsername: '@GoldenBetBot',
        brandName: 'GoldenBet',
        status: 'active',
        groupsCurrent: 2,
        groupsTotal: 2,
        adminCurrent: 2,
        adminTotal: 2,
        syncState: 'synced',
      },
    ],
  },
  {
    id: 'brand-c',
    brandLabel: 'C',
    brandName: 'SilverWin',
    accountCount: 1,
    standardGroupCount: 2,
    misalignedCount: 1,
    emptySlots: [],
    accounts: [
      {
        id: 'c1',
        platform: 'whatsapp',
        accountName: 'CS-Silver',
        phoneOrUsername: '+60199887766',
        brandName: 'SilverWin',
        status: 'active',
        groupsCurrent: 1,
        groupsTotal: 2,
        adminCurrent: 1,
        adminTotal: 2,
        syncState: 'synced',
      },
    ],
  },
];
